Repository devGnode/desbugs_selenium_testing, pull requests merged in 2020-03, with the labels that each got.

#1 Init page object pattern
  config/configuration.properties.template
  pom.xml
  src/main/java/fr/zenity/desbugs/Enum/Context.java
  src/main/java/fr/zenity/desbugs/Enum/DesbugsPage.java
  src/main/java/fr/zenity/desbugs/Enum/UrlEnvironment.java
  src/main/java/fr/zenity/desbugs/PagesObjects/AccountGeneralPage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/AccountIdentifierPage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/AccountSecurityPage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/BlogPage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/BugsPage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/EntreprisePage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/EntreprisesCreatedPage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/EntreprisesVerifyPage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/HomePage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/LearnMorePage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/LoggedHomePage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/LoginPage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/MyBugsCommentsPage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/MyBugsDetailsPage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/MyBugsFilesPage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/MyBugsPage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/NewBugDetailPage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/NewBugPlateformTypePage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/NewBugTypePage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/Page.java
  src/main/java/fr/zenity/desbugs/PagesObjects/RankingPage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/RegisterPage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/Test1.java
  src/main/java/fr/zenity/desbugs/PagesObjects/UsersPage.java
  src/main/java/fr/zenity/desbugs/Test.java
  src/main/java/fr/zenity/desbugs/configuration/PropertiesConfig.java
  src/main/java/fr/zenity/desbugs/driver/LocalDriver.java
  src/main/resources/config/urlEnv.properties
  src/test/java/fr/zenity/desbugs/runners/BaseRunner.java
  src/test/java/fr/zenity/desbugs/runners/TestRunner.java
  src/test/java/fr/zenity/desbugs/steps/Hook.java
  src/test/java/fr/zenity/desbugs/steps/Login.java
  src/test/java/fr/zenity/desbugs/steps/Test1.java
  src/test/resources/features/Login.feature
  src/test/resources/features/test.feature
Labels: enhancement

#2 Init base properties
  .gitignore
  src/main/java/fr/zenity/desbugs/Enum/Browser.java
  src/main/java/fr/zenity/desbugs/Enum/Context.java
  src/main/java/fr/zenity/desbugs/Enum/DesbugsPage.java
  src/main/java/fr/zenity/desbugs/Enum/UrlEnvironment.java
  src/main/java/fr/zenity/desbugs/configuration/PropertiesConfig.java
  src/main/java/fr/zenity/desbugs/driver/Driver.java
  src/main/java/fr/zenity/desbugs/driver/LocalDriver.java
  src/main/java/fr/zenity/desbugs/driverManager/WebDriverManager.java
  src/main/resources/config/browser.properties
  src/main/resources/config/browser.properties.template
  src/main/resources/config/configuration.properties
  src/main/resources/config/configuration.properties.template
  src/main/resources/config/urlEnv.properties
  src/main/resources/config/urlEnvironment.properties.template
  src/test/java/fr/zenity/desbugs/runners/BaseRunner.java
  src/test/java/fr/zenity/desbugs/runners/TestRunner.java
Labels: Fix or refactoring, enhancement

#3 Refactoring on all Framework
  .gitignore
  pom.xml
  src/main/java/fr/zenity/desbugs/Enum/DesbugsPage.java
  src/main/java/fr/zenity/desbugs/Enum/UrlEnvironment.java
  src/main/java/fr/zenity/desbugs/PagesObjects/AccountIdentifierPage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/AccountSecurityPage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/BlogPage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/BugsPage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/EntreprisePage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/EntreprisesCreatedPage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/EntreprisesVerifyPage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/HomePage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/LearnMorePage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/LoggedHomePage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/LoginPage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/MyBugsDetailsPage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/MyBugsFilesPage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/MyBugsPage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/NewBugDetailPage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/NewBugPlateformTypePage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/NewBugTypePage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/Page.java
  src/main/java/fr/zenity/desbugs/PagesObjects/RankingPage.java
  src/main/java/fr/zenity/desbugs/PagesObjects/RegisterPage.java
  src/main/resources/config/urlEnvironment.properties.template
  src/test/java/fr/zenity/desbugs/runners/BaseRunner.java
  src/test/java/fr/zenity/desbugs/runners/TestRunner.java
  src/test/java/fr/zenity/desbugs/step_definitions/Hook.java
  src/test/java/fr/zenity/desbugs/step_definitions/Login.java
  src/test/java/fr/zenity/desbugs/steps/Hook.java
  src/test/java/fr/zenity/desbugs/steps/Login.java
  src/test/resources/features/Login.feature
Labels: Fix or refactoring, enhancement

#6 Fix - kill process web browser after screnario
  src/test/java/fr/zenity/desbugs/runners/BaseRunner.java
Labels: Fix

#8 Implement - Allure 2 reporting
  .gitignore
  pom.xml
  src/main/java/fr/zenity/desbugs/Enum/UrlEnvironment.java
  src/main/resources/allure.properties
  src/main/resources/categories.json
  src/main/resources/environments.properties
  src/test/java/fr/zenity/desbugs/runners/TestRunner.java
Labels: enhancement

#7 Add readme.md
  Readme.md
Labels: documentation
